id: I1315E0E7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:22:50+00:00'
last_modified: '2022-06-07T14:53:45.927395+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20386
  title: བཟོ་གནས་སྐྲ་རྩེའི་ཆུ་ཐིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A33B:
      image_group_id: I1PD36367
      title: ''
      total_pages: 604
      order: 1
      base_file: A33B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
