id: P001741
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:17:51.826921
source_metadata:
  id: bdr:W20386
  title: བཟོ་གནས་སྐྲ་རྩེའི་ཆུ་ཐིགས
  author: ''
  volumes:
    4d6a113ddf014d02865cafedd0f2722c:
      image_group_id: I1PD36367
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
